Upgrade to node 18
einaregilsson/beanstalk-deploy pull request #106
Opened 2023-10-30 16:22 UTC by davecarlson

Node 16 is no longer the LTS, and out of support.

Node 18 is the new LTS release.

This is needed for any next 14+ project, as they have dropped support for v16

2023-11-29 15:03 UTC, jimreesman commented
👍

2024-01-31 17:12 UTC, sa2812 requested changes

2024-01-31 17:12 UTC, sa2812 commented on action.yml
> +  using: 'node18'
Can we change this to `node20` instead as recommended here? https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

2024-02-08 14:19 UTC, davecarlson commented on action.yml
> +  using: 'node18'
```suggestion
  using: 'node20'
```

2024-02-12 13:56 UTC, davecarlson commented
@keevie @gzur can we take a look at this ?

2024-02-12 14:57 UTC, keevie commented
looks good to me!

2024-02-14 13:04 UTC, merged

2024-02-16 17:11 UTC, benswinburne commented
@gzur any chance can you tag a release for this please?

2024-02-16 17:29 UTC, keevie commented
I can do this

2024-02-16 17:39 UTC, gzur commented
Be sure to update the README ;)

2024-02-16 19:59 UTC, benswinburne commented
@keevie Thank you